language: node_js
node_js:
  - "stable"
cache:
directories:
  - node_modules

before_script:
  - npm install -g loopback-cli
 
script:
  - npm install

deploy:
  provider: s3

  bucket: "lmsbackend"
  skip_cleanup: true
  region: "ap-southeast-2"
  acl: public_read
