language: node_js
node_js:
  - "stable"
cache:
directories:
  - node_modules

before_script:
  - npm install -g loopback-cli
 
script:
  - npm install

deploy:
  provider: s3
  access_key_id: "AKIAJAUTSDISZBU4RXUA"
  secret_access_key: "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"
  bucket: "lmsbackend"
  skip_cleanup: true
  region: "ap-southeast-2"
  acl: public_read
  local_dir: build
